apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dubinsky-pvc-01
  namespace: dubinsky-chatgpt-bot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi