apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  namespace: dubinsky-chatgpt-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      initContainers:
        - name: liquibase
          image: ghcr.io/jazonec/tg-bot_gpt-liquibase:latest  
          args: [
            "--changeLogFile=initial.postgres.yaml",
            "--url=jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(POSTGRES_DB)",
            "update"
          ]
          env:
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PORT

      containers:
        - name: telegram-bot
          image: ghcr.io/jazonec/tg-bot_gpt-telegram-bot:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: OAIKEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OAIKEY
            - name: OAIMODEL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OAIMODEL
            - name: OAIDALLEMODEL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OAIDALLEMODEL
            - name: BOTKEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BOTKEY
            - name: IMAGE_PRICE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: IMAGE_PRICE
