apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager
  namespace: dubinsky-chatgpt-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manager
  template:
    metadata:
      labels:
        app: user-manager
    spec:
      containers:
        - name: user-manager
          image: ghcr.io/jazonec/tg-bot_gpt-webconsoler:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: manager.py
            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: FLASK_SECRET_KEY
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PORT
