apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webconsole.fullname" . }}
  labels:
    {{- include "webconsole.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "webconsole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webconsole.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: webconsole
          image: "{{ .Values.image_webconsole.repository }}:{{ .Values.image_webconsole.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 8080
              name: http-port
          imagePullPolicy: {{ .Values.image_webconsole.pullPolicy }}
          env:
            - name: FLASK_APP
              value: manager.py
            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: FLASK_SECRET_KEY
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_DB
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: DB_PORT
